name: Basic Setup
author: Artem Gurzhii
author_email: artem.gurzhii@gmail.com
url: https://github.com/artemgurzhii/gulp-sass-jekyll
version: 0.2.0
markdown: redcarpet
highlighter: rouge
baseurl: ""
description: A starter project including full setup for Jekyll, Gulp, SASS, AutoPrefixer, BrowserSync, JS & CSS minification and other
exclude: ["node_modules", "gulpfile.babel.js", "package.json", "config.codekit", "data.json", "Gemfile", "Gemfile.lock", "LICENSE", "ToDo.txt", "assets/js/common.js", "assets/css/1-tools", "assets/css/2-modules", "assets/css/main.sass", "assets/css/main.css", "README.md"]
permalink: pretty
sass:
  sass_dir: assets/css/main.sass
  style: expanded
