name: Basic Setup
author: Artem Hurzhii
author_email: artem.gurzhii@gmail.com
url: https://github.com/artemgurzhii/Gulp-Sass-Jade-Jekyll
version: 0.1.3
markdown: redcarpet
highlighter: rouge
description: A starter project including full setup for Jekyll, Jade, Gulp, SASS, AutoPrefixer, BrowserSync, JS & CSS minification and other
exclude: ["node_modules", "gulpfile.js", "package.json", "config.codekit", "bower_components"]
permalink: pretty
sass:
  sass_dir: assets/css/main.sass
  style: expanded
